name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Run a one-line script
        run: |
          echo "This is a simple test"
          echo "This is an actual secret: ${{ secrets.DUMMY_SECRET }}"
          echo "This is a non-existing secret: ${{ secrets.SMART_SECRET }}"
