name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'The Terraform command to run (init/apply/destroy)'
        required: true
        default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_compartment_id: ${{ secrets.TF_VAR_COMPARTMENT_ID }}
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_TENANCY_OCID }}
      TF_VAR_user_ocid: ${{ secrets.TF_VAR_USER_OCID }}
      TF_VAR_fingerprint: ${{ secrets.TF_VAR_FINGERPRINT }}
      TF_VAR_private_key: ${{ secrets.TF_VAR_PRIVATE_KEY }}
      TF_VAR_ssh_authorized_keys: ${{ secrets.TF_VAR_SSH_AUTHORIZED_KEYS }}
      TF_VAR_bucket_name: ${{ secrets.TF_VAR_BUCKET_NAME }}
      TF_VAR_endpoint: ${{ secrets.TF_VAR_ENDPOINT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.command == 'init'
        run: terraform init

      - name: Apply Terraform
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.command == 'apply'
        run: |
          terraform init
          terraform plan -out .tfplan
          terraform apply -auto-approve

      - name: Destroy Terraform
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.command == 'destroy'
        run: |
          terraform init
          terraform destroy -auto-approve
